### ISSUE TITLE
Issues getting started (newb problems) with the github auth.

### ISSUE THREAD

**Issue by jisaacstone** [foundweekends/conscript#69] opened 2014-12-03 18:48 UTC
I got stuck immediately after installing conscript. I could not install `g8`

> $ ~/bin/cs n8han/giter8
> An unexpected error occurred: Please check your internet connection.
> And if you're using a pre-release version of Java, please try with
> a final release version.
> Exception message: Unexpected response status: 403

After getting advice from another scala engineer in my company I found that I needed to add a github token to my config:

1. go to github.com and login
2.   go to settings -> Applications
3.  Click "Generate new token" in Personal access tokens
4.  copy the generated token
5.  add gh.access=<token from #4> to ~/.conscript/config
6. re run ~/bin/cs n8han/giter8

I think these steps should be mentioned in the getting started documentation, and probably in the error code as well. It looks like they are hinted at under the __Private Repositories__ heading, but seems to be necessary for public repos as well?

I can add a section to the `readme.md` if you'd like but messing with the error code stuff should probably wait until after I've learned the language. But the error mentions 2 possible issues, neither of which is correct. Maybe just adding the third would possibility be enough? I could conceivably tackle that as well.

**Comment by michalmela** [comment] 2016-05-14 12:02
Maybe the HTTP error status should be checked against a list of known possible problems and appropriate message then shown?
Then if there is no known problem the error message could advise to re-visit documentation or sth.

What I mean is, the current message advises to set up the gh access token (it doesn't say where to put it which led me to this page exactly, but maybe I've not been reading the docs carefully enough), but this may only be helpful if the HTTP status was 403, as shown in @jisaacstone's quote:

> Exception message: Unexpected response status: 403

In my case the error was 301, caused by the fact that giter8 was apparently moved from n8han/giter8 to foundweekends/giter8 , so the new error message is not really helfpul.

Also, as possible separate issues:

 * maybe the JAR installer could ask for GH access token during installation? (I could investigate and try to do this, but would just like to know if it makes sense)
 * should not the HTTP client follow redirections? (same as above)

**Comment by eed3si9n** [comment] 2016-05-15 19:08
@michalmela 

> Maybe the HTTP error status should be checked against a list of known possible problems and appropriate message then shown?

I think that's a good idea. I'm going to open a separate Github issue for that and close this one.

**Closed** 2016-05-15 19:08 UTC

**Comment by eed3si9n** [comment] 2016-05-15 19:18
@michalmela As per two possible separate issues:

- I think the majority of the use cases are on public repo like giter8, so I don't think it would be a good UX to force this to all new users.
-  HTTP client follow redirections. +1. I'm going to open a Github issue on this. pull request would be welcome.

**Comment by jerzygangi** [comment] 2016-06-12 02:38
A note to future Googlers:

If you come here after having run `n8han/giter8`, you need to instead run `foundweekends/giter8` since the repository was moved.
